### PR TITLE
Fix upgrading of bandits to normal troops

### LINKED ISSUE #5: Upgrade prisoners does not respect disciplinarian perk
If you have bandit troops with you that only have one upgrade path, e.g. forest bandit, you are able to upgrade them even without having the disciplinarian perk.

This should be taken into consideration when upgrading.

### PR DESCRIPTION
**Pull request by MLNW**
- Fix #5 
- Refactor upgrade and recruitment logic
- Improve upgrade troop information

### CODE REVIEW

**Comment by MLNW** [comment]
Rebased on top of master

**Comment by Urky** [comment]
Merged into my branch TakeUpgradeCostIntoAccount

**Comment by MLNW** [comment]
The idea was to merge this onto master and then you rebasing on top of that.

Since there are new conflicts I will do the same for this branch.

**Comment by MLNW** [comment]
Rebased on top of master, ready for review @tbeswick96

**Comment by MLNW** [comment]
Since @Urky already merged this PR into his work and did a manual merge of changes I will abandon this PR. Otherwise a manual merge would have to be executed once more.

**Pull request closed without merging**
